### ISSUE TITLE
Add GitHub Repo Link

### ISSUE THREAD

**Issue by makiftutuncu** [makiftutuncu/makiftutuncu.github.io#7]
Add a link/banner/badge to the webpage so this repository can be opened easily.

**Comment by SreejaMandla** [comment]
can i have this issue assigned?

**Comment by makiftutuncu** [comment]
> can i have this issue assigned?
> 
> 

Of course. Feel free to work on it and send a PR. 👍🏻 @SreejaMandla

**Comment by nafisreza** [comment]
fixed #9

**Comment by nafisreza** [comment]
@makiftutuncu  you should close this issue also.
